Feature/issue#28
Necrelox/SkillZBox pull request #34
Opened 2022-05-08 18:41 UTC by Necrelox

2022-05-09 10:52 UTC, kevin-smrt requested changes

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
Je suis allé me renseigné sur l'internet mondial, on en avait parlé, tu peux mettre des `&&` a la place de tes ternaires.

```ts
message: "checkPostContainMailANDUserANDPassword : Missing parameters" + (!postData.email && " email") + (!postData.username && " username") + (!postData.password && " password") + "."
```

L'operateur `&&` vérifie que les deux variables sont `true`, si il y en a une qui est fausse il fait rien du tout. Dans ce cas tu lui demande si, par exemple, `postData.email` est `false` (!postData.email). Il l'est, donc il te renvoie `true` et forcement `" email"` est `true` donc il te l'affiche.

J'ai testé avec postman et c'est ok. Tu verras souvent cette formulation en React (le &&) dans a peu près les mêmes conditions -> `{nomDeVariable && <Composant>}`

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
Pareil que pour la méthode `checkPostContainMailANDUserANDPassword`, tout tes ternaires avec une string vide tu peux les remplacer par l'opérateur `&&` du coup je vais pas te les review tous, mais au moins tu le sais !

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/controller/account/utils/accountUtils.ts
> +                code: "AccountUtilsError",
Go faire des enums pour tes codes d'erreurs

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/database/skillzboxDatabaseKnex.ts
> +
Pourquoi t'as deux lignes vide ici ? mdr

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/server.ts
> +        this._app.use("/account", new SzbxController.AccountController().getRouter());
Ce serait bien peut être de séparer les routes (c'est pas vraiment une route mais t'as capté) parce que plus tard çava être le bordel sinon, t'en penses quoi ?

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/server.ts
> +    }
Ce serait cool d'avoir un console.log du port utilisé, comme le truc par defaut qui dit "Server is now running on port ${port}"

2022-05-09 10:52 UTC, kevin-smrt commented on back/src/server/tools/mail/mailer.ts
> +            code: "MailerError",
Enum pour tes codes d'erreur ici aussi

2022-05-10 06:56 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
Merci je vais tester ça alors 👍👍

2022-05-10 06:56 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
C'est ok

2022-05-10 06:57 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +                code: "AccountUtilsError",
J'y compte bien, il faut que je trouve quelque chose qui pourrait être sympa à mettre en place, car on aura beaucoup de code d'erreurs

2022-05-10 06:58 UTC, Necrelox commented on back/src/server/database/skillzboxDatabaseKnex.ts
> +
Ptdr je sais pas 😂 je vais régler ça merci !

2022-05-10 07:00 UTC, Necrelox commented on back/src/server/server.ts
> +        this._app.use("/account", new SzbxController.AccountController().getRouter());
Je sais pas encore pour le moment.
C'est une bonne idée, mais je me dis que c'est des catégories de routes, et si je me rappelle ; on en aura 6.

Mais franchement pourquoi pas ! Si tu as une idée je prend !

2022-05-10 07:01 UTC, Necrelox commented on back/src/server/server.ts
> +    }
Par rapport à ça je l'ai retiré exprès dans un des derniers commit : Correction CodeFactor
Selon lui : en général on ne met pas de console.log en production.
Du coup j'ai corrigé ça en les retirant.

2022-05-10 07:01 UTC, Necrelox commented on back/src/server/tools/mail/mailer.ts
> +            code: "MailerError",
Yep !

2022-05-13 11:27 UTC, kevin-smrt requested changes

2022-05-14 20:01 UTC, Necrelox commented on back/src/server/controller/account/accountController.ts
> +                }
non.

2022-05-14 20:05 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +                message: "checkPostContainMailORUserANDPassword : Missing parameters" + (postData.email && " email") + (postData.username && " username") + (postData.password && " password") + "."
Vu en vocal, c'es bon !

2022-05-18 10:49 UTC, kevin-smrt requested changes

2022-05-18 10:49 UTC, kevin-smrt commented on back/src/server/controller/account/utils/accountUtils.ts
> +            };
Il faudrait enlever le verify login du message d'erreur

2022-05-18 10:55 UTC, kevin-smrt requested changes

2022-05-18 10:55 UTC, kevin-smrt commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
Dans cette fonction il faudrait qu'on check si l'utilisateur existe déjà avant de le créer.

2022-05-18 11:00 UTC, kevin-smrt commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
Github Copilot (<3) me propose ça :

const userExist: SzBxModel.User.IModelUser[] = await SzBxModel.User.User.select(user);
if (userExist && userExist.length > 0) {
    throw {
            code: CodeError.ACCOUNT_UTILS_CREATE_USER,            message: MessageError.USER_ALREADY_EXIST
            };
        }

2022-05-19 08:37 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
C'est réglé !

2022-05-19 08:37 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +    }
C'est réglé !

2022-05-19 08:38 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +                code: "AccountUtilsError",
C'est réglé ! (Peut-être amélioré à l'avenir, mais on se dédira d'un ticket pour)

2022-05-19 08:38 UTC, Necrelox commented on back/src/server/database/skillzboxDatabaseKnex.ts
> +
C'est réglé !

2022-05-19 08:38 UTC, Necrelox commented on back/src/server/server.ts
> +        this._app.use("/account", new SzbxController.AccountController().getRouter());
C'est réglé !

2022-05-19 08:39 UTC, Necrelox commented on back/src/server/server.ts
> +    }
C'est réglé !

2022-05-19 08:39 UTC, Necrelox commented on back/src/server/tools/mail/mailer.ts
> +            code: "MailerError",
C'est réglé !

2022-05-19 08:41 UTC, Necrelox commented on back/src/server/controller/account/accountController.ts
> +            });
C'est réglé !

2022-05-19 08:41 UTC, Necrelox commented on back/src/server/controller/account/accountController.ts
> +            });
C'est réglé !

2022-05-19 08:41 UTC, Necrelox commented on back/src/server/controller/account/accountController.ts
> +        }
C'est réglé !

2022-05-19 08:42 UTC, Necrelox commented on back/src/server/controller/account/utils/accountUtils.ts
> +            };
Je suis d'accord !

2022-05-19 08:46 UTC, Necrelox commented
Revoir les "shadowed name" que l'on peut retrouver dans le namespace de SzbxModel
(exemple : `export const Room = _Room;` )

Je ferai peut être un ticket pour changer les namespaces, par une solution plus "moderne".

2022-05-19 16:35 UTC, kevin-smrt requested changes

2022-05-19 16:35 UTC, kevin-smrt commented on back/src/server/controller/account/accountController.ts
> +            });
Je reçois le message seulement si j'enlève le point d'exclamation, il faudrait l'enlever du coup je pense

2022-05-22 12:26 UTC, kevin-smrt approved these changes

2022-05-22 12:49 UTC, merged