:sparkles: Update user profile
Necrelox/SkillZBox pull request #62
Opened 2022-07-24 11:58 UTC by kevin-smrt

# Description
Add redux user store and can now update user profile

# Checklist
Please remove the irrelevant checkboxes.

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] All my variables, functions and files have appropriate names.
- [x] My code is upgradable.
- [x] There is no new unused or commented code.
- [x] Each functions or methods have only one responsability.
- [x] I have tested my own code.

2022-07-24 16:17 UTC, kevin-smrt commented on front/src/helpers/utils.ts
> +};
Cette partie est importante, c'est l'auto login, faut que je la rename d'ailleurs.
J'ai un peu fais a l'arrache, je suis sur qu'il y a mieux à faire en terme de logique :thinking:

2022-07-25 08:17 UTC, Necrelox commented on front/src/helpers/utils.ts
> +};
Oui effectivement il est possible de faire mieux.
Par exemple faire une fonction plus générique pour le call del'api

2022-09-07 21:18 UTC, Necrelox requested changes
Franchement c'est propre

2022-09-07 21:18 UTC, Necrelox commented on front/src/functions/register/register.ts
>      setIsButtonDisabled(true);
il faut que tu fasses plus attentions au fonction async
si elles sont async
met un await là où tu l'appelles

2022-09-07 21:18 UTC, Necrelox commented on front/src/functions/register/register.ts
>      setIsButtonDisabled(false);
Pareil que en haut c'est une fonction async

2022-09-07 21:18 UTC, Necrelox commented on front/src/functions/register/register.ts
>      setIsButtonDisabled(false);
Pareil que en haut c'est une fonction async

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/apiCalls.ts
> +  return await fetch(url, {
comme a dit code factor pas de await avec le return c'est useless

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/apiCalls.ts
> +  const response = await callApi(Endpoint.local.USER.ME, ApiMethod.GET, {
grrr Pas de type il faudrait une interface de ce que tu attends

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/apiCalls.ts
> +  const data = await response.json();
pareil du typage

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/apiCalls.ts
> +  return await response.json();
pareil que plus haut le return await est inutile

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/apiCalls.ts
> +  return await response.json();
pareil que plus haut sur le return await

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/apiCalls.ts
> +  return await response.json();
Return await inutile

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/utils.ts
> +};
En soit ces fonction sont assez generique peut être changer le nomdu pramètre serait mieux

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/utils.ts
> +};
je pensais que tu utiliserais reddux

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/utils.ts
> +  const userToken = getUserTokenFromLocalStorage();
pas de type :(

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/utils.ts
> +  return await getUserInfosFromDatabase(userToken);
return await inutile

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/utils.ts
> +    const userInfoFromDatabase = await getUserData(dispatch);
Manque de typage

2022-09-07 21:18 UTC, Necrelox commented on front/src/helpers/utils.ts
> +  getAndStoreUserInformations(dispatch, setModalContent);
ici c'est une fonction async !

2022-09-07 21:18 UTC, Necrelox commented on front/src/interfaces/APIResponses.interface.ts
> +}
Le nom du fichier fais penser à autre choses

Peut être rajouter le AUTH

2022-09-07 21:18 UTC, Necrelox commented on front/src/redux/store.ts
> +const reducer = (state: any, action: any): any => {
pas fan du any

2022-09-11 17:26 UTC, Necrelox approved these changes

2022-09-17 11:23 UTC, merged