#55 : supression du token après update du password
Necrelox/SkillZBox pull request #66
Opened 2022-07-25 10:16 UTC by Necrelox

2022-07-29 19:26 UTC, kevin-smrt approved these changes

2022-07-31 12:40 UTC, kevin-smrt requested changes

2022-07-31 12:40 UTC, kevin-smrt commented on back/src/server/database/databaseQueries/UserQueries/index.ts
> +                }, trx);
Il faut deconnecter le user avec la variable isConnected (je crois)

2022-07-31 23:02 UTC, Necrelox commented
je me permet d'ajouter une mini correction sur le login-cli, lors d'une reco il ne mettait pas en active :
- device
- ip
- macaddress

2022-11-25 09:46 UTC, closed without merging